"""Add Topic and ChatMessage models; update File model with processing fields

Revision ID: e245950f6721
Revises: 1d1970ab2c84
Create Date: 2025-11-18 18:27:59.577554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM


# revision identifiers, used by Alembic.
revision: str = 'e245950f6721'
down_revision: Union[str, None] = '1d1970ab2c84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create ENUM types manually BEFORE creating tables
    # Use create_type=False in table definitions to prevent auto-creation
    op.execute("CREATE TYPE processingstatus AS ENUM ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')")
    op.execute("CREATE TYPE messagerole AS ENUM ('USER', 'ASSISTANT', 'SYSTEM')")
    
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('topic_name', sa.String(length=500), nullable=False),
    sa.Column('introduction', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_id'), 'topics', ['id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', ENUM('USER', 'ASSISTANT', 'SYSTEM', name='messagerole', create_type=False), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('message_metadata', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.add_column('files', sa.Column('file_type', sa.String(length=50), nullable=True))
    op.add_column('files', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('files', sa.Column('processing_status', ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='processingstatus', create_type=False), nullable=False))
    op.add_column('files', sa.Column('uploaded_at', sa.DateTime(), nullable=False))
    op.add_column('files', sa.Column('processed_at', sa.DateTime(), nullable=True))
    op.alter_column('files', 'file_url',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('files', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('files', 'file_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('files', 'processed_at')
    op.drop_column('files', 'uploaded_at')
    op.drop_column('files', 'processing_status')
    op.drop_column('files', 'file_size')
    op.drop_column('files', 'file_type')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_topics_id'), table_name='topics')
    op.drop_table('topics')

    # Drop ENUM types
    op.execute("DROP TYPE IF EXISTS messagerole")
    op.execute("DROP TYPE IF EXISTS processingstatus")
    # ### end Alembic commands ###